#!/bin/bash
chmod +x script12.sh
mkdir -p LAB1
cd LAB1
mkdir -p STEP1; cd STEP1; touch -c $HOME/res2
cd $HOME; cp res1 LAB1/STEP1; cp res1 LAB1
rm -f $HOME/res1
find LAB1 > res2; echo "Таким был файл res1:" >> res2
cat $HOME/LAB1/res1 >> res2
echo "Конец файла res1" >> res2
cat res2
find LAB1/res1 LAB1/STEP1/res1 -delete
